<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><RestorePackagesWithLockFile>true</RestorePackagesWithLockFile></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AssignmentFinder.Data/AssignmentFinder.Data.csproj" />
    <ProjectReference Include="../AssignmentFinder.Browser/AssignmentFinder.Browser.csproj" />
  </ItemGroup>
</Project>
